version: '3.8'

services:
  sanctum:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - BYPASS_OIDC=true
      - SESSION_SECRET=dev-secret-key
      - INSTANCE_ID=dev-local
      - COUCHDB_URL=http://couchdb:5984
      - COUCHDB_DATABASE=sanctum_dev
      - COUCHDB_USERNAME=admin
      - COUCHDB_PASSWORD=password
    depends_on:
      - couchdb
    volumes:
      - .:/app
      - /app/node_modules
    command: npx nodemon index.js
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
    restart: unless-stopped

  couchdb:
    image: couchdb:3.3
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - couchdb_data:/opt/couchdb/data
    restart: unless-stopped

volumes:
  couchdb_data: