version: '3.8'

services:
  sanctum:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "28080:8080"
    env_file:
      - .env.dev.sanctum
    volumes:
      - .:/app
      - /app/node_modules
    command: npx nodemon index.js
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
    restart: unless-stopped

networks:
  default:
    name: development